name: Test my CLI setup

on: 
  push: 
    branches: 
      - main
      - feature/*

jobs: 
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Install myCLI
        uses: ./.github/actions/cli-action
        with:
          version: '1.2.3'
      
      - name: Verify CLI installation
        run: |
          echo "Check the version of CLI"
          mycli --version

  save_cache: 
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: save the cache
        uses: actions/cache@v4
        with:
          path: ~/.mycli/cache
          key: ${{ runner.os }}-mycli-${{ inputs.version }}
